"""
AI-generated utility functions for data processing.
Generated by Claude Code - test file for Spectre AI detection.
"""

from typing import List, Dict, Optional
import json
import re


def sanitize_input(text: str) -> str:
    """Sanitize user input by removing potentially dangerous characters.

    This function removes HTML tags, script injections, and normalizes
    whitespace to prevent XSS attacks and other injection vulnerabilities.
    """
    # Remove HTML tags
    cleaned = re.sub(r'<[^>]+>', '', text)
    # Remove script patterns
    cleaned = re.sub(r'javascript:', '', cleaned, flags=re.IGNORECASE)
    # Normalize whitespace
    cleaned = ' '.join(cleaned.split())
    return cleaned.strip()


def calculate_fibonacci(n: int) -> List[int]:
    """Calculate Fibonacci sequence up to n numbers.

    Uses an iterative approach for O(n) time complexity and O(n) space.
    Returns the complete sequence as a list.
    """
    if n <= 0:
        return []
    if n == 1:
        return [0]

    sequence = [0, 1]
    for i in range(2, n):
        sequence.append(sequence[i-1] + sequence[i-2])
    return sequence


def merge_sort(arr: List[int]) -> List[int]:
    """Implement merge sort algorithm.

    Divides the array into halves recursively and merges them back
    in sorted order. Time complexity: O(n log n).
    """
    if len(arr) <= 1:
        return arr

    mid = len(arr) // 2
    left = merge_sort(arr[:mid])
    right = merge_sort(arr[mid:])

    return _merge(left, right)


def _merge(left: List[int], right: List[int]) -> List[int]:
    """Merge two sorted lists into a single sorted list."""
    result = []
    i = j = 0

    while i < len(left) and j < len(right):
        if left[i] <= right[j]:
            result.append(left[i])
            i += 1
        else:
            result.append(right[j])
            j += 1

    result.extend(left[i:])
    result.extend(right[j:])
    return result


def parse_config(config_str: str) -> Dict:
    """Parse a JSON configuration string with validation.

    Validates required fields and returns a normalized config dict.
    Raises ValueError for invalid configurations.
    """
    try:
        config = json.loads(config_str)
    except json.JSONDecodeError as e:
        raise ValueError(f"Invalid JSON configuration: {e}")

    required_fields = ['name', 'version', 'settings']
    for field in required_fields:
        if field not in config:
            raise ValueError(f"Missing required field: {field}")

    return {
        'name': str(config['name']),
        'version': str(config['version']),
        'settings': config['settings'],
        'debug': config.get('debug', False),
    }


class DataProcessor:
    """Process and transform data collections.

    Provides methods for filtering, mapping, and aggregating data
    with support for chaining operations.
    """

    def __init__(self, data: List[Dict]):
        self._data = data
        self._filters = []

    def filter_by(self, key: str, value) -> 'DataProcessor':
        """Add a filter condition."""
        self._filters.append((key, value))
        return self

    def execute(self) -> List[Dict]:
        """Execute all filters and return results."""
        result = self._data
        for key, value in self._filters:
            result = [item for item in result if item.get(key) == value]
        return result

    def aggregate(self, key: str) -> Dict[str, int]:
        """Count occurrences of each value for the given key."""
        counts: Dict[str, int] = {}
        for item in self._data:
            val = str(item.get(key, 'unknown'))
            counts[val] = counts.get(val, 0) + 1
        return counts

    def transform(self, func) -> List:
        """Apply a transformation function to each item."""
        return [func(item) for item in self._data]
